HAI
I HAS A JERRY ITZ 1
I HAS A RAT ITZ 0
I HAS A MICE
I HAS A FINGAR ITZ 0

IM IN YR HOUSE UPPIN YR FINGAR TIL BOTH SAEM FINGAR AN 10
    VISIBLE MICE
    BTW I LIKEY JERRY
    JERRY R SUM OF MICE AN 1
    JERRY R MICE
    RAT R MICE
IM OUTTA YR HOUSE
